-- MSSQL Version of Nepal Province, District, and Municipality Data
-- Based on official local level codes from Nepal Government
-- Code format: P (Province) + DD (District) + LL (Local Level Serial) = PDDLL

-- Create Provinces table
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'provinces')
BEGIN
    CREATE TABLE provinces (
        province_id TINYINT PRIMARY KEY,
        province_name VARCHAR(40) NOT NULL
    );
END
GO

-- Insert provinces data
IF NOT EXISTS (SELECT * FROM provinces WHERE province_id = 1)
BEGIN
    INSERT INTO provinces (province_id, province_name) VALUES
    (1, 'Province No. 1'),
    (2, 'Province No. 2'),
    (3, 'Bagmati Pradesh'),
    (4, 'Gandaki Pradesh'),
    (5, 'Lumbini Province'),
    (6, 'Karnali Province'),
    (7, 'Sudurpashchim Province');
END
GO

-- Create Districts table with 3-digit district_id (PDD format from PDF)
-- Examples: 101 = Province 1, District 01; 201 = Province 2, District 01; etc.
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'districts')
BEGIN
    CREATE TABLE districts (
        district_id VARCHAR(3) PRIMARY KEY,
        district_name VARCHAR(50) NOT NULL,
        province_id INT NOT NULL,
        CONSTRAINT FK_districts_provinces FOREIGN KEY (province_id) REFERENCES provinces(province_id)
    );
END
GO

-- Insert districts data with 3-digit IDs from PDF (PDD format)
IF NOT EXISTS (SELECT * FROM districts WHERE district_id = '101')
BEGIN
    INSERT INTO districts (district_id, district_name, province_id) VALUES
    -- Province 1 (1XX)
    ('101', 'Taplejung', 1),
    ('102', 'Sankhuwasabha', 1),
    ('103', 'Solukhumbu', 1),
    ('104', 'Okhaldhunga', 1),
    ('105', 'Khotang', 1),
    ('106', 'Bhojpur', 1),
    ('107', 'Dhankuta', 1),
    ('108', 'Terhathum', 1),
    ('109', 'Panchthar', 1),
    ('110', 'Ilam', 1),
    ('111', 'Jhapa', 1),
    ('112', 'Morang', 1),
    ('113', 'Sunsari', 1),
    ('114', 'Udayapur', 1),
    -- Province 2 (2XX)
    ('201', 'Saptari', 2),
    ('202', 'Siraha', 2),
    ('203', 'Dhanusha', 2),
    ('204', 'Mahottari', 2),
    ('205', 'Sarlahi', 2),
    ('206', 'Rautahat', 2),
    ('207', 'Bara', 2),
    ('208', 'Parsa', 2),
    -- Province 3 (3XX)
    ('301', 'Dolakha', 3),
    ('302', 'Sindhupalchok', 3),
    ('303', 'Rasuwa', 3),
    ('304', 'Dhading', 3),
    ('305', 'Nuwakot', 3),
    ('306', 'Kathmandu', 3),
    ('307', 'Bhaktapur', 3),
    ('308', 'Lalitpur', 3),
    ('309', 'Kavrepalanchok', 3),
    ('310', 'Ramechhap', 3),
    ('311', 'Sindhuli', 3),
    ('312', 'Makwanpur', 3),
    ('313', 'Chitwan', 3),
    -- Province 4 (4XX)
    ('401', 'Gorkha', 4),
    ('402', 'Manang', 4),
    ('403', 'Mustang', 4),
    ('404', 'Myagdi', 4),
    ('405', 'Kaski', 4),
    ('406', 'Lamjung', 4),
    ('407', 'Tanahun', 4),
    ('408', 'Nawalparasi East', 4),
    ('409', 'Syangja', 4),
    ('410', 'Parbat', 4),
    ('411', 'Baglung', 4),
    -- Province 5 (5XX)
    ('501', 'Rukum East', 5),
    ('502', 'Rolpa', 5),
    ('503', 'Pyuthan', 5),
    ('504', 'Gulmi', 5),
    ('505', 'Arghakhanchi', 5),
    ('506', 'Palpa', 5),
    ('507', 'Nawalparasi West', 5),
    ('508', 'Rupandehi', 5),
    ('509', 'Kapilbastu', 5),
    ('510', 'Dang', 5),
    ('511', 'Banke', 5),
    ('512', 'Bardiya', 5),
    -- Province 6 (6XX)
    ('601', 'Dolpa', 6),
    ('602', 'Mugu', 6),
    ('603', 'Humla', 6),
    ('604', 'Jumla', 6),
    ('605', 'Kalikot', 6),
    ('606', 'Dailekh', 6),
    ('607', 'Jajarkot', 6),
    ('608', 'Rukum West', 6),
    ('609', 'Salyan', 6),
    ('610', 'Surkhet', 6),
    -- Province 7 (7XX)
    ('701', 'Bajura', 7),
    ('702', 'Bajhang', 7),
    ('703', 'Darchula', 7),
    ('704', 'Baitadi', 7),
    ('705', 'Dadeldhura', 7),
    ('706', 'Doti', 7),
    ('707', 'Achham', 7),
    ('708', 'Kailali', 7),
    ('709', 'Kanchanpur', 7);
END
GO

-- Create Municipalities table
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'municipalities')
BEGIN
    CREATE TABLE municipalities (
        municipality_id INT PRIMARY KEY IDENTITY(1,1),
        municipality_name VARCHAR(100) NOT NULL,
        district_id VARCHAR(3) NOT NULL,
        municipality_code VARCHAR(5) NOT NULL UNIQUE,
        local_level_type VARCHAR(30) NULL,
        CONSTRAINT FK_Municipalities_districts FOREIGN KEY (district_id) REFERENCES districts(district_id)
    );
END
GO

-- Fix district_id column size if table exists with wrong size
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('districts') AND name = 'district_id' AND max_length < 3)
BEGIN
    ALTER TABLE districts ALTER COLUMN district_id VARCHAR(3) NOT NULL;
END
GO

-- Fix district_id column size in municipalities if table exists
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('municipalities') AND name = 'district_id' AND max_length < 3)
BEGIN
    ALTER TABLE municipalities ALTER COLUMN district_id VARCHAR(3) NOT NULL;
END
GO

-- Fix local_level_type column size if table exists with smaller size
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('municipalities') AND name = 'local_level_type' AND max_length < 30)
BEGIN
    ALTER TABLE municipalities ALTER COLUMN local_level_type VARCHAR(30) NULL;
END
GO

-- Insert municipalities data with codes from PDF
IF NOT EXISTS (SELECT * FROM municipalities WHERE municipality_code = '10101')
BEGIN
    INSERT INTO municipalities (municipality_name, district_id, municipality_code, local_level_type) VALUES
    -- Province 1, District 101 - Taplejung
    ('Phaktanlung Rural Municipality', '101', '10101', 'Rural Municipality'),
    ('Mikwakhola Rural Municipality', '101', '10102', 'Rural Municipality'),
    ('Meringden Rural Municipality', '101', '10103', 'Rural Municipality'),
    ('Maiwakhola Rural Municipality', '101', '10104', 'Rural Municipality'),
    ('Aatharai Tribeni Rural Municipality', '101', '10105', 'Rural Municipality'),
    ('Phungling Urban Municipality', '101', '10106', 'Urban Municipality'),
    ('Pathivara Yangwarak Rural Municipality', '101', '10107', 'Rural Municipality'),
    ('Sirijanga Rural Municipality', '101', '10108', 'Rural Municipality'),
    ('Sidingba Rural Municipality', '101', '10109', 'Rural Municipality'),
    -- Province 1, District 102 - Sankhuwasabha
    ('Bhotkhola Rural Municipality', '102', '10201', 'Rural Municipality'),
    ('Makalu Rural Municipality', '102', '10202', 'Rural Municipality'),
    ('Silichong Rural Municipality', '102', '10203', 'Rural Municipality'),
    ('Chichila Rural Municipality', '102', '10204', 'Rural Municipality'),
    ('Sabhapokhari Rural Municipality', '102', '10205', 'Rural Municipality'),
    ('Khandabari Urban Municipality', '102', '10206', 'Urban Municipality'),
    ('Panchakhapan Urban Municipality', '102', '10207', 'Urban Municipality'),
    ('Chainapur Urban Municipality', '102', '10208', 'Urban Municipality'),
    ('Madi Urban Municipality', '102', '10209', 'Urban Municipality'),
    ('Dharmadevi Urban Municipality', '102', '10210', 'Urban Municipality'),
    -- Province 1, District 103 - Solukhumbu
    ('Khumbu Pasanglhamu Rural Municipality', '103', '10301', 'Rural Municipality'),
    ('Mahakulung Rural Municipality', '103', '10302', 'Rural Municipality'),
    ('Sotang Rural Municipality', '103', '10303', 'Rural Municipality'),
    ('Mapya Dudhkoshi Rural Municipality', '103', '10304', 'Rural Municipality'),
    ('Thulung Dudhkoshi Rural Municipality', '103', '10305', 'Rural Municipality'),
    ('Necha Salyan Rural Municipality', '103', '10306', 'Rural Municipality'),
    ('Solu Dhudhakunda Urban Municipality', '103', '10307', 'Urban Municipality'),
    ('Likhu Pike Rural Municipality', '103', '10308', 'Rural Municipality'),
    -- Province 1, District 104 - Okhaldhunga
    ('Chishankhu Gadhi Rural Municipality', '104', '10401', 'Rural Municipality'),
    ('Siddhicharan Urban Municipality', '104', '10402', 'Urban Municipality'),
    ('Molung Rural Municipality', '104', '10403', 'Rural Municipality'),
    ('Khiji Demba Rural Municipality', '104', '10404', 'Rural Municipality'),
    ('Likhu Rural Municipality', '104', '10405', 'Rural Municipality'),
    ('Champadevi Rural Municipality', '104', '10406', 'Rural Municipality'),
    ('Sunkoshi Rural Municipality', '104', '10407', 'Rural Municipality'),
    ('Manebhanjyang Rural Municipality', '104', '10408', 'Rural Municipality'),
    -- Province 1, District 105 - Khotang
    ('Kepilasgadhi Rural Municipality', '105', '10501', 'Rural Municipality'),
    ('Aiselukharka Rural Municipality', '105', '10502', 'Rural Municipality'),
    ('Rawa Besi Rural Municipality', '105', '10503', 'Rural Municipality'),
    ('Halesi Tuwachung Urban Municipality', '105', '10504', 'Urban Municipality'),
    ('Diktel Rupakot Majhuwagadhi Urban Municipality', '105', '10505', 'Urban Municipality'),
    ('Sakela Rural Municipality', '105', '10506', 'Rural Municipality'),
    ('Diprung Chuichumma Rural Municipality', '105', '10507', 'Rural Municipality'),
    ('Khotehang Rural Municipality', '105', '10508', 'Rural Municipality'),
    ('Jante Dhunga Rural Municipality', '105', '10509', 'Rural Municipality'),
    ('Baraha Pokhari Rural Municipality', '105', '10510', 'Rural Municipality'),
    -- Province 1, District 106 - Bhojpur
    ('Shadananda Urban Municipality', '106', '10601', 'Urban Municipality'),
    ('Salpa Silichho Rural Municipality', '106', '10602', 'Rural Municipality'),
    ('Temkemaiyum Rural Municipality', '106', '10603', 'Rural Municipality'),
    ('Bhojpur Urban Municipality', '106', '10604', 'Urban Municipality'),
    ('Arun Rural Municipality', '106', '10605', 'Rural Municipality'),
    ('Pauwa Dunma Rural Municipality', '106', '10606', 'Rural Municipality'),
    ('Ramprasad Rai Rural Municipality', '106', '10607', 'Rural Municipality'),
    ('Hatuwagadhi Rural Municipality', '106', '10608', 'Rural Municipality'),
    ('Aamchowk Rural Municipality', '106', '10609', 'Rural Municipality'),
    -- Province 1, District 107 - Dhankuta
    ('Mahalaxmi Urban Municipality', '107', '10701', 'Urban Municipality'),
    ('Pakhribas Urban Municipality', '107', '10702', 'Urban Municipality'),
    ('Chhathar Jorpati Rural Municipality', '107', '10703', 'Rural Municipality'),
    ('Dhankuta Urban Municipality', '107', '10704', 'Urban Municipality'),
    ('Shahidbhumi Rural Municipality', '107', '10705', 'Rural Municipality'),
    ('Sangurigadhi Rural Municipality', '107', '10706', 'Rural Municipality'),
    ('Chaubise Rural Municipality', '107', '10707', 'Rural Municipality'),
    -- Province 1, District 108 - Terhathum
    ('Aatharai Rural Municipality', '108', '10801', 'Rural Municipality'),
    ('Phedap Rural Municipality', '108', '10802', 'Rural Municipality'),
    ('Menchhayayem Rural Municipality', '108', '10803', 'Rural Municipality'),
    ('Myanglung Urban Municipality', '108', '10804', 'Urban Municipality'),
    ('Laligurans Urban Municipality', '108', '10805', 'Urban Municipality'),
    ('Chhathar Rural Municipality', '108', '10806', 'Rural Municipality'),
    -- Province 1, District 109 - Panchthar
    ('Yangbarak Rural Municipality', '109', '10901', 'Rural Municipality'),
    ('Hilihan Rural Municipality', '109', '10902', 'Rural Municipality'),
    ('Falelung Rural Municipality', '109', '10903', 'Rural Municipality'),
    ('Phidim Urban Municipality', '109', '10904', 'Urban Municipality'),
    ('Falgunanda Rural Municipality', '109', '10905', 'Rural Municipality'),
    ('Kummayak Rural Municipality', '109', '10906', 'Rural Municipality'),
    ('Tumbewa Rural Municipality', '109', '10907', 'Rural Municipality'),
    ('Miklajung Rural Municipality', '109', '10908', 'Rural Municipality'),
    -- Province 1, District 110 - Ilam
    ('Mai Jogmai Rural Municipality', '110', '11001', 'Rural Municipality'),
    ('Sandakpur Rural Municipality', '110', '11002', 'Rural Municipality'),
    ('Ilam Urban Municipality', '110', '11003', 'Urban Municipality'),
    ('Deumai Urban Municipality', '110', '11004', 'Urban Municipality'),
    ('Fakfokathum Rural Municipality', '110', '11005', 'Rural Municipality'),
    ('Mangsebung Rural Municipality', '110', '11006', 'Rural Municipality'),
    ('Chulachuli Rural Municipality', '110', '11007', 'Rural Municipality'),
    ('Mai Urban Municipality', '110', '11008', 'Urban Municipality'),
    ('Suryodaya Urban Municipality', '110', '11009', 'Urban Municipality'),
    ('Rong Rural Municipality', '110', '11010', 'Rural Municipality'),
    -- Province 1, District 111 - Jhapa
    ('Mechinagar Urban Municipality', '111', '11101', 'Urban Municipality'),
    ('Buddhashanti Rural Municipality', '111', '11102', 'Rural Municipality'),
    ('Arjundhara Urban Municipality', '111', '11103', 'Urban Municipality'),
    ('Kankai Urban Municipality', '111', '11104', 'Urban Municipality'),
    ('Shivasatakshi Urban Municipality', '111', '11105', 'Urban Municipality'),
    ('Kamal Rural Municipality', '111', '11106', 'Rural Municipality'),
    ('Damak Urban Municipality', '111', '11107', 'Urban Municipality'),
    ('Gauradaha Urban Municipality', '111', '11108', 'Urban Municipality'),
    ('Gauriganj Rural Municipality', '111', '11109', 'Rural Municipality'),
    ('Jhapa Rural Municipality', '111', '11110', 'Rural Municipality'),
    ('Barhadashi Rural Municipality', '111', '11111', 'Rural Municipality'),
    ('Birtamod Urban Municipality', '111', '11112', 'Urban Municipality'),
    ('Haldibari Rural Municipality', '111', '11113', 'Rural Municipality'),
    ('Bhadrapur Urban Municipality', '111', '11114', 'Urban Municipality'),
    ('Kachanakawal Rural Municipality', '111', '11115', 'Rural Municipality'),
    -- Province 1, District 112 - Morang
    ('Miklajung Rural Municipality', '112', '11201', 'Rural Municipality'),
    ('Letang Urban Municipality', '112', '11202', 'Urban Municipality'),
    ('Kerabari Rural Municipality', '112', '11203', 'Rural Municipality'),
    ('Sundarharaicha Urban Municipality', '112', '11204', 'Urban Municipality'),
    ('Belbari Urban Municipality', '112', '11205', 'Urban Municipality'),
    ('Kanepokhari Rural Municipality', '112', '11206', 'Rural Municipality'),
    ('Pathari Shanishchare Urban Municipality', '112', '11207', 'Urban Municipality'),
    ('Urlabari Urban Municipality', '112', '11208', 'Urban Municipality'),
    ('Ratuwamai Urban Municipality', '112', '11209', 'Urban Municipality'),
    ('Sunwarshi Urban Municipality', '112', '11210', 'Urban Municipality'),
    ('Rangeli Urban Municipality', '112', '11211', 'Urban Municipality'),
    ('Gramthan Rural Municipality', '112', '11212', 'Rural Municipality'),
    ('Budhiganga Rural Municipality', '112', '11213', 'Rural Municipality'),
    ('Biratnagar Metropolitian City', '112', '11214', 'Metropolitan City'),
    ('Katahari Rural Municipality', '112', '11215', 'Rural Municipality'),
    ('Dhanapalthan Rural Municipality', '112', '11216', 'Rural Municipality'),
    ('Jahada Rural Municipality', '112', '11217', 'Rural Municipality'),
    -- Province 1, District 113 - Sunsari
    ('Dharan Sub-Metropolitian City', '113', '11301', 'Sub-Metropolitan City'),
    ('Barahachhetra Urban Municipality', '113', '11302', 'Urban Municipality'),
    ('Koshi Rural Municipality', '113', '11303', 'Rural Municipality'),
    ('Bhokraha Narsingh Rural Municipality', '113', '11304', 'Rural Municipality'),
    ('Ramdhuni Urban Municipality', '113', '11305', 'Urban Municipality'),
    ('Itahari Sub-Metropolitian City', '113', '11306', 'Sub-Metropolitan City'),
    ('Duhabi Urban Municipality', '113', '11307', 'Urban Municipality'),
    ('Gadhi Rural Municipality', '113', '11308', 'Rural Municipality'),
    ('Inaruwa Urban Municipality', '113', '11309', 'Urban Municipality'),
    ('Harinagar Rural Municipality', '113', '11310', 'Rural Municipality'),
    ('Dewangunj Rural Municipality', '113', '11311', 'Rural Municipality'),
    ('Barju Rural Municipality', '113', '11312', 'Rural Municipality'),
    -- Province 1, District 114 - Udayapur
    ('Belaka Urban Municipality', '114', '11401', 'Urban Municipality'),
    ('Chaudandigadhi Urban Municipality', '114', '11402', 'Urban Municipality'),
    ('Triyuga Urban Municipality', '114', '11403', 'Urban Municipality'),
    ('Rautamai Rural Municipality', '114', '11404', 'Rural Municipality'),
    ('Limchungbung Rural Municipality', '114', '11405', 'Rural Municipality'),
    ('Tapli Rural Municipality', '114', '11406', 'Rural Municipality'),
    ('Katari Urban Municipality', '114', '11407', 'Urban Municipality'),
    ('Udayapurgadhi Rural Municipality', '114', '11408', 'Rural Municipality'),
    -- Province 2, District 201 - Saptari
    ('Saptakoshi Urban Municipality', '201', '20101', 'Urban Municipality'),
    ('Kanchanrup Urban Municipality', '201', '20102', 'Urban Municipality'),
    ('Agnisair Krishna Sabaran Rural Municipality', '201', '20103', 'Rural Municipality'),
    ('Rupani Rural Municipality', '201', '20104', 'Rural Municipality'),
    ('Shambhunath Urban Municipality', '201', '20105', 'Urban Municipality'),
    ('Khadak Urban Municipality', '201', '20106', 'Urban Municipality'),
    ('Surunga Urban Municipality', '201', '20107', 'Urban Municipality'),
    ('Balan-Bihul Rural Municipality', '201', '20108', 'Rural Municipality'),
    ('Bode Barsain Urban Municipality', '201', '20109', 'Urban Municipality'),
    ('Dakneshwori Urban Municipality', '201', '20110', 'Urban Municipality'),
    ('Rajgadh Rural Municipality', '201', '20111', 'Rural Municipality'),
    ('Bishnupur Rural Municipality', '201', '20112', 'Rural Municipality'),
    ('Rajbiraj Urban Municipality', '201', '20113', 'Urban Municipality'),
    ('Mahadewa Rural Municipality', '201', '20114', 'Rural Municipality'),
    ('Tirahut Rural Municipality', '201', '20115', 'Rural Municipality'),
    ('Hanumannagar Kankalini Urban Municipality', '201', '20116', 'Urban Municipality'),
    ('Tilathi Koiladi Rural Municipality', '201', '20117', 'Rural Municipality'),
    ('Chhinnamasta Rural Municipality', '201', '20118', 'Rural Municipality'),
    -- Province 2, District 202 - Siraha
    ('Lahan Urban Municipality', '202', '20201', 'Urban Municipality'),
    ('Dhangadhimai Urban Municipality', '202', '20202', 'Urban Municipality'),
    ('Golbazar Urban Municipality', '202', '20203', 'Urban Municipality'),
    ('Mirchaiya Urban Municipality', '202', '20204', 'Urban Municipality'),
    ('Karjanha Urban Municipality', '202', '20205', 'Urban Municipality'),
    ('Kalyanpur Urban Municipality', '202', '20206', 'Urban Municipality'),
    ('Naraha Rural Municipality', '202', '20207', 'Rural Municipality'),
    ('Bishnupur Rural Municipality', '202', '20208', 'Rural Municipality'),
    ('Arnama Rural Municipality', '202', '20209', 'Rural Municipality'),
    ('Sukhipur Urban Municipality', '202', '20210', 'Urban Municipality'),
    ('Laxmipur Patari Rural Municipality', '202', '20211', 'Rural Municipality'),
    ('Sakhuwa Nankarkatti Rural Municipality', '202', '20212', 'Rural Municipality'),
    ('Bhagawanpur Rural Municipality', '202', '20213', 'Rural Municipality'),
    ('Nawarajpur Rural Municipality', '202', '20214', 'Rural Municipality'),
    ('Bariyarpatti Rural Municipality', '202', '20215', 'Rural Municipality'),
    ('Aurahi Rural Municipality', '202', '20216', 'Rural Municipality'),
    ('Siraha Urban Municipality', '202', '20217', 'Urban Municipality'),
    -- Province 2, District 203 - Dhanusha
    ('Ganeshman Charnath Urban Municipality', '203', '20301', 'Urban Municipality'),
    ('Dhanushadham Urban Municipality', '203', '20302', 'Urban Municipality'),
    ('Mithila Urban Municipality', '203', '20303', 'Urban Municipality'),
    ('Bateshwor Rural Municipality', '203', '20304', 'Rural Municipality'),
    ('Chhireshwornath Urban Municipality', '203', '20305', 'Urban Municipality'),
    ('Laxminiya Rural Municipality', '203', '20306', 'Rural Municipality'),
    ('Mithila Bihari Urban Municipality', '203', '20307', 'Urban Municipality'),
    ('Hansapur Urban Municipality', '203', '20308', 'Urban Municipality'),
    ('Sabaila Urban Municipality', '203', '20309', 'Urban Municipality'),
    ('Shahidnagar Urban Municipality', '203', '20310', 'Urban Municipality'),
    ('Kamala Urban Municipality', '203', '20311', 'Urban Municipality'),
    ('Janak Nandini Rural Municipality', '203', '20312', 'Rural Municipality'),
    ('Bideha Urban Municipality', '203', '20313', 'Urban Municipality'),
    ('Aurahi Urban Municipality', '203', '20314', 'Urban Municipality'),
    ('Janakpurdham Sub-Metropolitian City', '203', '20315', 'Sub-Metropolitan City'),
    ('Dhanauji Rural Municipality', '203', '20316', 'Rural Municipality'),
    ('Nagarain Urban Municipality', '203', '20317', 'Urban Municipality'),
    ('Mukhiyapatti Musaharmiya Rural Municipality', '203', '20318', 'Rural Municipality'),
    -- Province 2, District 204 - Mahottari
    ('Bardibas Urban Municipality', '204', '20401', 'Urban Municipality'),
    ('Gaushala Urban Municipality', '204', '20402', 'Urban Municipality'),
    ('Sonama Rural Municipality', '204', '20403', 'Rural Municipality'),
    ('Aurahi Urban Municipality', '204', '20404', 'Urban Municipality'),
    ('Bhangaha Urban Municipality', '204', '20405', 'Urban Municipality'),
    ('Loharpatti Urban Municipality', '204', '20406', 'Urban Municipality'),
    ('Balawa Urban Municipality', '204', '20407', 'Urban Municipality'),
    ('Ram Gopalpur Urban Municipality', '204', '20408', 'Urban Municipality'),
    ('Samsi Rural Municipality', '204', '20409', 'Rural Municipality'),
    ('Manara Shisawa Urban Municipality', '204', '20410', 'Urban Municipality'),
    ('Ekadara Rural Municipality', '204', '20411', 'Rural Municipality'),
    ('Mahottari Rural Municipality', '204', '20412', 'Rural Municipality'),
    ('Pipara Rural Municipality', '204', '20413', 'Rural Municipality'),
    ('Matihani Urban Municipality', '204', '20414', 'Urban Municipality'),
    ('Jaleshwor Urban Municipality', '204', '20415', 'Urban Municipality'),
    -- Province 2, District 205 - Sarlahi
    ('Lalbandi Urban Municipality', '205', '20501', 'Urban Municipality'),
    ('Hariwan Urban Municipality', '205', '20502', 'Urban Municipality'),
    ('Bagmati Urban Municipality', '205', '20503', 'Urban Municipality'),
    ('Barahathawa Urban Municipality', '205', '20504', 'Urban Municipality'),
    ('Haripur Urban Municipality', '205', '20505', 'Urban Municipality'),
    ('Ishworpur Urban Municipality', '205', '20506', 'Urban Municipality'),
    ('Haripurwa Urban Municipality', '205', '20507', 'Urban Municipality'),
    ('Parsa Rural Municipality', '205', '20508', 'Rural Municipality'),
    ('Brahmapuri Rural Municipality', '205', '20509', 'Rural Municipality'),
    ('Chandranagar Rural Municipality', '205', '20510', 'Rural Municipality'),
    ('Kabilashi Urban Municipality', '205', '20511', 'Urban Municipality'),
    ('Chakraghatta Rural Municipality', '205', '20512', 'Rural Municipality'),
    ('Basbariya Rural Municipality', '205', '20513', 'Rural Municipality'),
    ('Dhanakaul Rural Municipality', '205', '20514', 'Rural Municipality'),
    ('Ramnagar Rural Municipality', '205', '20515', 'Rural Municipality'),
    ('Balara Urban Municipality', '205', '20516', 'Urban Municipality'),
    ('Godaita Urban Municipality', '205', '20517', 'Urban Municipality'),
    ('Bishnu Rural Municipality', '205', '20518', 'Rural Municipality'),
    ('Kaudena Rural Municipality', '205', '20519', 'Rural Municipality'),
    ('Malangawa Urban Municipality', '205', '20520', 'Urban Municipality'),
    -- Province 2, District 206 - Rautahat
    ('Chandrapur Urban Municipality', '206', '20601', 'Urban Municipality'),
    ('Gujara Urban Municipality', '206', '20602', 'Urban Municipality'),
    ('Phatuwa Bijayapur Urban Municipality', '206', '20603', 'Urban Municipality'),
    ('Katahariya Urban Municipality', '206', '20604', 'Urban Municipality'),
    ('Brindaban Urban Municipality', '206', '20605', 'Urban Municipality'),
    ('Gadhimai Urban Municipality', '206', '20606', 'Urban Municipality'),
    ('Madhav Narayan Urban Municipality', '206', '20607', 'Urban Municipality'),
    ('Garuda Urban Municipality', '206', '20608', 'Urban Municipality'),
    ('Dewahi Gonahi Urban Municipality', '206', '20609', 'Urban Municipality'),
    ('Maulapur Urban Municipality', '206', '20610', 'Urban Municipality'),
    ('Boudhimai Urban Municipality', '206', '20611', 'Urban Municipality'),
    ('Paroha Urban Municipality', '206', '20612', 'Urban Municipality'),
    ('Rajpur Urban Municipality', '206', '20613', 'Urban Municipality'),
    ('Yamunamai Rural Municipality', '206', '20614', 'Rural Municipality'),
    ('Durga Bhagawati Rural Municipality', '206', '20615', 'Rural Municipality'),
    ('Rajdevi Urban Municipality', '206', '20616', 'Urban Municipality'),
    ('Gaur Urban Municipality', '206', '20617', 'Urban Municipality'),
    ('Ishanath Urban Municipality', '206', '20618', 'Urban Municipality'),
    -- Province 2, District 207 - Bara
    ('Nijagadh Urban Municipality', '207', '20701', 'Urban Municipality'),
    ('Kolhabi Urban Municipality', '207', '20702', 'Urban Municipality'),
    ('Jitpur Simara Sub-Metropolitian City', '207', '20703', 'Sub-Metropolitan City'),
    ('Parawanipur Rural Municipality', '207', '20704', 'Rural Municipality'),
    ('Prasauni Rural Municipality', '207', '20705', 'Rural Municipality'),
    ('Bishrampur Rural Municipality', '207', '20706', 'Rural Municipality'),
    ('Pheta Rural Municipality', '207', '20707', 'Rural Municipality'),
    ('Kalaiya Sub-Metropolitian City', '207', '20708', 'Sub-Metropolitan City'),
    ('Karaiyamai Rural Municipality', '207', '20709', 'Rural Municipality'),
    ('Baragadhi Rural Municipality', '207', '20710', 'Rural Municipality'),
    ('Aadarsha Kotwal Rural Municipality', '207', '20711', 'Rural Municipality'),
    ('Simroungadh Urban Municipality', '207', '20712', 'Urban Municipality'),
    ('Pacharauta Urban Municipality', '207', '20713', 'Urban Municipality'),
    ('Mahagadhimai Urban Municipality', '207', '20714', 'Urban Municipality'),
    ('Devtal Rural Municipality', '207', '20715', 'Rural Municipality'),
    ('Subarna Rural Municipality', '207', '20716', 'Rural Municipality'),
    -- Province 2, District 208 - Parsa
    ('Thori Rural Municipality', '208', '20801', 'Rural Municipality'),
    ('Jirabhawani Rural Municipality', '208', '20802', 'Rural Municipality'),
    ('Jagarnathpur Rural Municipality', '208', '20803', 'Rural Municipality'),
    ('Paterwa Sugauli Rural Municipality', '208', '20804', 'Rural Municipality'),
    ('Sakhuwa Prasauni Rural Municipality', '208', '20805', 'Rural Municipality'),
    ('Parsagadhi Urban Municipality', '208', '20806', 'Urban Municipality'),
    ('Birgunj Metropolitian City', '208', '20807', 'Metropolitan City'),
    ('Bahudarmai Urban Municipality', '208', '20808', 'Urban Municipality'),
    ('Pokhariya Urban Municipality', '208', '20809', 'Urban Municipality'),
    ('Kalikamai Rural Municipality', '208', '20810', 'Rural Municipality'),
    ('Dhobini Rural Municipality', '208', '20811', 'Rural Municipality'),
    ('Chhipaharmai Rural Municipality', '208', '20812', 'Rural Municipality'),
    ('Pakaha Mainpur Rural Municipality', '208', '20813', 'Rural Municipality'),
    ('Bindabasini Rural Municipality', '208', '20814', 'Rural Municipality'),
    -- Province 3, District 301 - Dolakha
    ('Gaurishankar Rural Municipality', '301', '30101', 'Rural Municipality'),
    ('Bigu Rural Municipality', '301', '30102', 'Rural Municipality'),
    ('Kalinchowk Rural Municipality', '301', '30103', 'Rural Municipality'),
    ('Baiteshwor Rural Municipality', '301', '30104', 'Rural Municipality'),
    ('Jiri Urban Municipality', '301', '30105', 'Urban Municipality'),
    ('Tamakoshi Rural Municipality', '301', '30106', 'Rural Municipality'),
    ('Melung Rural Municipality', '301', '30107', 'Rural Municipality'),
    ('Shailung Rural Municipality', '301', '30108', 'Rural Municipality'),
    ('Bhimeshwor Urban Municipality', '301', '30109', 'Urban Municipality'),
    -- Province 3, District 302 - Sindhupalchok
    ('Bhotekoshi Rural Municipality', '302', '30201', 'Rural Municipality'),
    ('Jugal Rural Municipality', '302', '30202', 'Rural Municipality'),
    ('Panchpokhari Thangpal Rural Municipality', '302', '30203', 'Rural Municipality'),
    ('Helambu Rural Municipality', '302', '30204', 'Rural Municipality'),
    ('Melanchi Urban Municipality', '302', '30205', 'Urban Municipality'),
    ('Indrawoti Rural Municipality', '302', '30206', 'Rural Municipality'),
    ('Choutara Sangachowkgadhi Urban Municipality', '302', '30207', 'Urban Municipality'),
    ('Balephi Rural Municipality', '302', '30208', 'Rural Municipality'),
    ('Bahrabise Urban Municipality', '302', '30209', 'Urban Municipality'),
    ('Tripurasundari Rural Municipality', '302', '30210', 'Rural Municipality'),
    ('Lisankhu Pakhar Rural Municipality', '302', '30211', 'Rural Municipality'),
    ('Sunkoshi Rural Municipality', '302', '30212', 'Rural Municipality'),
    -- Province 3, District 303 - Rasuwa
    ('Gosaikunda Rural Municipality', '303', '30301', 'Rural Municipality'),
    ('Aamachhodingmo Rural Municipality', '303', '30302', 'Rural Municipality'),
    ('Uttargaya Rural Municipality', '303', '30303', 'Rural Municipality'),
    ('Shuva Kalika Rural Municipality', '303', '30304', 'Rural Municipality'),
    ('Naukunda Rural Municipality', '303', '30305', 'Rural Municipality'),
    -- Province 3, District 304 - Dhading
    ('Rubi Valley Rural Municipality', '304', '30401', 'Rural Municipality'),
    ('Khaniyabas Rural Municipality', '304', '30402', 'Rural Municipality'),
    ('Ganga Jamuna Rural Municipality', '304', '30403', 'Rural Municipality'),
    ('Tripurasundari Rural Municipality', '304', '30404', 'Rural Municipality'),
    ('Netrawati Dabjong Rural Municipality', '304', '30405', 'Rural Municipality'),
    ('Nilkhantha Urban Municipality', '304', '30406', 'Urban Municipality'),
    ('Jwalamukhi Rural Municipality', '304', '30407', 'Rural Municipality'),
    ('Siddhalek Rural Municipality', '304', '30408', 'Rural Municipality'),
    ('Benighat Rorang Rural Municipality', '304', '30409', 'Rural Municipality'),
    ('Gajuri Rural Municipality', '304', '30410', 'Rural Municipality'),
    ('Galchhi Rural Municipality', '304', '30411', 'Rural Municipality'),
    ('Thakre Rural Municipality', '304', '30412', 'Rural Municipality'),
    ('Dhunibenshi Urban Municipality', '304', '30413', 'Urban Municipality'),
    -- Province 3, District 305 - Nuwakot
    ('Dupcheshwor Rural Municipality', '305', '30501', 'Rural Municipality'),
    ('Tadi Rural Municipality', '305', '30502', 'Rural Municipality'),
    ('Suryagadhi Rural Municipality', '305', '30503', 'Rural Municipality'),
    ('Bidur Urban Municipality', '305', '30504', 'Urban Municipality'),
    ('Kispang Rural Municipality', '305', '30505', 'Rural Municipality'),
    ('Myagang Rural Municipality', '305', '30506', 'Rural Municipality'),
    ('Tarakeshwor Rural Municipality', '305', '30507', 'Rural Municipality'),
    ('Belkotgadhi Urban Municipality', '305', '30508', 'Urban Municipality'),
    ('Likhu Rural Municipality', '305', '30509', 'Rural Municipality'),
    ('Panchakanya Rural Municipality', '305', '30510', 'Rural Municipality'),
    ('Shivapuri Rural Municipality', '305', '30511', 'Rural Municipality'),
    ('Kakani Rural Municipality', '305', '30512', 'Rural Municipality'),
    -- Province 3, District 306 - Kathmandu
    ('Shankharapur Urban Municipality', '306', '30601', 'Urban Municipality'),
    ('Kageshwori Manahara Urban Municipality', '306', '30602', 'Urban Municipality'),
    ('Gokarneshwor Urban Municipality', '306', '30603', 'Urban Municipality'),
    ('Budhanilkhantha Urban Municipality', '306', '30604', 'Urban Municipality'),
    ('Tokha Urban Municipality', '306', '30605', 'Urban Municipality'),
    ('Tarakeshwor Urban Municipality', '306', '30606', 'Urban Municipality'),
    ('Nagarjun Urban Municipality', '306', '30607', 'Urban Municipality'),
    ('Kathmandu Metropolitian City', '306', '30608', 'Metropolitan City'),
    ('Kirtipur Urban Municipality', '306', '30609', 'Urban Municipality'),
    ('Chandragiri Urban Municipality', '306', '30610', 'Urban Municipality'),
    ('Dakshinkali Urban Municipality', '306', '30611', 'Urban Municipality'),
    -- Province 3, District 307 - Bhaktapur
    ('Changunarayan Urban Municipality', '307', '30701', 'Urban Municipality'),
    ('Bhaktapur Urban Municipality', '307', '30702', 'Urban Municipality'),
    ('Madhyapur Thimi Urban Municipality', '307', '30703', 'Urban Municipality'),
    ('Suryabinayak Urban Municipality', '307', '30704', 'Urban Municipality'),
    -- Province 3, District 308 - Lalitpur
    ('Mahalaxmi Urban Municipality', '308', '30801', 'Urban Municipality'),
    ('Lalitpur Metropolitian City', '308', '30802', 'Metropolitan City'),
    ('Godawari Urban Municipality', '308', '30803', 'Urban Municipality'),
    ('Konjyosom Rural Municipality', '308', '30804', 'Rural Municipality'),
    ('Mahankal Rural Municipality', '308', '30805', 'Rural Municipality'),
    ('Bagmati Rural Municipality', '308', '30806', 'Rural Municipality'),
    -- Province 3, District 309 - Kavrepalanchok
    ('Chauri Deurali Rural Municipality', '309', '30901', 'Rural Municipality'),
    ('Bhumlu Rural Municipality', '309', '30902', 'Rural Municipality'),
    ('Mandan Deupur Urban Municipality', '309', '30903', 'Urban Municipality'),
    ('Banepa Urban Municipality', '309', '30904', 'Urban Municipality'),
    ('Dhulikhel Urban Municipality', '309', '30905', 'Urban Municipality'),
    ('Panchkhal Urban Municipality', '309', '30906', 'Urban Municipality'),
    ('Temal Rural Municipality', '309', '30907', 'Rural Municipality'),
    ('Namobuddha Urban Municipality', '309', '30908', 'Urban Municipality'),
    ('Panauti Urban Municipality', '309', '30909', 'Urban Municipality'),
    ('Bethanchowk Rural Municipality', '309', '30910', 'Rural Municipality'),
    ('Roshi Rural Municipality', '309', '30911', 'Rural Municipality'),
    ('Mahabharat Rural Municipality', '309', '30912', 'Rural Municipality'),
    ('Khanikhola Rural Municipality', '309', '30913', 'Rural Municipality'),
    -- Province 3, District 310 - Ramechhap
    ('Umakunda Rural Municipality', '310', '31001', 'Rural Municipality'),
    ('Gokulganga Rural Municipality', '310', '31002', 'Rural Municipality'),
    ('Likhu Tamakoshi Rural Municipality', '310', '31003', 'Rural Municipality'),
    ('Ramechhap Urban Municipality', '310', '31004', 'Urban Municipality'),
    ('Manthali Urban Municipality', '310', '31005', 'Urban Municipality'),
    ('Khandadevi Rural Municipality', '310', '31006', 'Rural Municipality'),
    ('Doramba Rural Municipality', '310', '31007', 'Rural Municipality'),
    ('Sunapati Rural Municipality', '310', '31008', 'Rural Municipality'),
    -- Province 3, District 311 - Sindhuli
    ('Dudhouli Urban Municipality', '311', '31101', 'Urban Municipality'),
    ('Phikkal Rural Municipality', '311', '31102', 'Rural Municipality'),
    ('Tinpatan Rural Municipality', '311', '31103', 'Rural Municipality'),
    ('Golanjor Rural Municipality', '311', '31104', 'Rural Municipality'),
    ('Kamalamai Urban Municipality', '311', '31105', 'Urban Municipality'),
    ('Sunkoshi Rural Municipality', '311', '31106', 'Rural Municipality'),
    ('Ghyanglekha Rural Municipality', '311', '31107', 'Rural Municipality'),
    ('Marin Rural Municipality', '311', '31108', 'Rural Municipality'),
    ('Hariharpurgaghi Rural Municipality', '311', '31109', 'Rural Municipality'),
    -- Province 3, District 312 - Makwanpur
    ('Indrasarowar Rural Municipality', '312', '31201', 'Rural Municipality'),
    ('Thaha Urban Municipality', '312', '31202', 'Urban Municipality'),
    ('Kailash Rural Municipality', '312', '31203', 'Rural Municipality'),
    ('Raksirang Rural Municipality', '312', '31204', 'Rural Municipality'),
    ('Manahari Rural Municipality', '312', '31205', 'Rural Municipality'),
    ('Hetauda Sub-Metropolitian City', '312', '31206', 'Sub-Metropolitan City'),
    ('Bhimphedi Rural Municipality', '312', '31207', 'Rural Municipality'),
    ('Makawanpurgadhi Rural Municipality', '312', '31208', 'Rural Municipality'),
    ('Bakaiya Rural Municipality', '312', '31209', 'Rural Municipality'),
    ('Bagmati Rural Municipality', '312', '31210', 'Rural Municipality'),
    -- Province 3, District 313 - Chitwan
    ('Rapti Urban Municipality', '313', '31301', 'Urban Municipality'),
    ('Kalika Urban Municipality', '313', '31302', 'Urban Municipality'),
    ('Ichchha Kamana Rural Municipality', '313', '31303', 'Rural Municipality'),
    ('Bharatpur Metropolitian City', '313', '31304', 'Metropolitan City'),
    ('Ratnanagar Urban Municipality', '313', '31305', 'Urban Municipality'),
    ('Khairahani Urban Municipality', '313', '31306', 'Urban Municipality'),
    ('Madi Urban Municipality', '313', '31307', 'Urban Municipality'),
    -- Province 4, District 401 - Gorkha
    ('Chumanubri Rural Municipality', '401', '40101', 'Rural Municipality'),
    ('Ajirkot Rural Municipality', '401', '40102', 'Rural Municipality'),
    ('Barpak Sulikot Rural Municipality', '401', '40103', 'Rural Municipality'),
    ('Dharche Rural Municipality', '401', '40104', 'Rural Municipality'),
    ('Aarughat Rural Municipality', '401', '40105', 'Rural Municipality'),
    ('Bhimsenthapa Rural Municipality', '401', '40106', 'Rural Municipality'),
    ('Siranchowk Rural Municipality', '401', '40107', 'Rural Municipality'),
    ('Palungtar Urban Municipality', '401', '40108', 'Urban Municipality'),
    ('Gorkha Urban Municipality', '401', '40109', 'Urban Municipality'),
    ('Shahid Lakhan Rural Municipality', '401', '40110', 'Rural Municipality'),
    ('Gandaki Rural Municipality', '401', '40111', 'Rural Municipality'),
    -- Province 4, District 402 - Manang
    ('Narpa Bhumi Rural Municipality', '402', '40201', 'Rural Municipality'),
    ('Manang Ngisyang Rural Municipality', '402', '40202', 'Rural Municipality'),
    ('Chame Rural Municipality', '402', '40203', 'Rural Municipality'),
    ('Nason Rural Municipality', '402', '40204', 'Rural Municipality'),
    -- Province 4, District 403 - Mustang
    ('Lo Ghekar Damodarkunda Rural Municipality', '403', '40301', 'Rural Municipality'),
    ('Gharpajhong Rural Municipality', '403', '40302', 'Rural Municipality'),
    ('Varagung Muktichhetra Rural Municipality', '403', '40303', 'Rural Municipality'),
    ('Lomanthang Rural Municipality', '403', '40304', 'Rural Municipality'),
    ('Thasang Rural Municipality', '403', '40305', 'Rural Municipality'),
    -- Province 4, District 404 - Myagdi
    ('Annapurna Rural Municipality', '404', '40401', 'Rural Municipality'),
    ('Raghuganga Rural Municipality', '404', '40402', 'Rural Municipality'),
    ('Dhawalagiri Rural Municipality', '404', '40403', 'Rural Municipality'),
    ('Malika Rural Municipality', '404', '40404', 'Rural Municipality'),
    ('Mangala Rural Municipality', '404', '40405', 'Rural Municipality'),
    ('Beni Urban Municipality', '404', '40406', 'Urban Municipality'),
    -- Province 4, District 405 - Kaski
    ('Madi Rural Municipality', '405', '40501', 'Rural Municipality'),
    ('Machhapuchchhre Rural Municipality', '405', '40502', 'Rural Municipality'),
    ('Annapurna Rural Municipality', '405', '40503', 'Rural Municipality'),
    ('Pokhara Metropolitian City', '405', '40504', 'Metropolitan City'),
    ('Rupa Rural Municipality', '405', '40505', 'Rural Municipality'),
    -- Province 4, District 406 - Lamjung
    ('Dordi Rural Municipality', '406', '40601', 'Rural Municipality'),
    ('Marshyangdi Rural Municipality', '406', '40602', 'Rural Municipality'),
    ('Kwhola Sothar Rural Municipality', '406', '40603', 'Rural Municipality'),
    ('Madhya Nepal Urban Municipality', '406', '40604', 'Urban Municipality'),
    ('Bensi Shahar Urban Municipality', '406', '40605', 'Urban Municipality'),
    ('Sundarbazar Urban Municipality', '406', '40606', 'Urban Municipality'),
    ('Rainas Urban Municipality', '406', '40607', 'Urban Municipality'),
    ('Dudhapokhari Rural Municipality', '406', '40608', 'Rural Municipality'),
    -- Province 4, District 407 - Tanahun
    ('Bhanu Urban Municipality', '407', '40701', 'Urban Municipality'),
    ('Byas Urban Municipality', '407', '40702', 'Urban Municipality'),
    ('Myagde Rural Municipality', '407', '40703', 'Rural Municipality'),
    ('Shuklagandaki Urban Municipality', '407', '40704', 'Urban Municipality'),
    ('Bhimad Urban Municipality', '407', '40705', 'Urban Municipality'),
    ('Ghiring Rural Municipality', '407', '40706', 'Rural Municipality'),
    ('Rhishing Rural Municipality', '407', '40707', 'Rural Municipality'),
    ('Devghat Rural Municipality', '407', '40708', 'Rural Municipality'),
    ('Bandipur Rural Municipality', '407', '40709', 'Rural Municipality'),
    ('Aanbu Khaireni Rural Municipality', '407', '40710', 'Rural Municipality'),
    -- Province 4, District 408 - Nawalparasi East
    ('Gaidakot Urban Municipality', '408', '40801', 'Urban Municipality'),
    ('Bulingtar Rural Municipality', '408', '40802', 'Rural Municipality'),
    ('Baudikali Rural Municipality', '408', '40803', 'Rural Municipality'),
    ('Hupsekot Rural Municipality', '408', '40804', 'Rural Municipality'),
    ('Devchuli Urban Municipality', '408', '40805', 'Urban Municipality'),
    ('Kawasoti Urban Municipality', '408', '40806', 'Urban Municipality'),
    ('Madhya Bindu Urban Municipality', '408', '40807', 'Urban Municipality'),
    ('Binayi Tribeni Rural Municipality', '408', '40808', 'Rural Municipality'),
    -- Province 4, District 409 - Syangja
    ('Putalibazar Urban Municipality', '409', '40901', 'Urban Municipality'),
    ('Phedikhola Rural Municipality', '409', '40902', 'Rural Municipality'),
    ('Aandhikhola Rural Municipality', '409', '40903', 'Rural Municipality'),
    ('Arjun Choupari Rural Municipality', '409', '40904', 'Rural Municipality'),
    ('Bhirkot Urban Municipality', '409', '40905', 'Urban Municipality'),
    ('Biruwa Rural Municipality', '409', '40906', 'Rural Municipality'),
    ('Harinas Rural Municipality', '409', '40907', 'Rural Municipality'),
    ('Chapakot Urban Municipality', '409', '40908', 'Urban Municipality'),
    ('Walling Urban Municipality', '409', '40909', 'Urban Municipality'),
    ('Galyang Urban Municipality', '409', '40910', 'Urban Municipality'),
    ('Kaligandaki Rural Municipality', '409', '40911', 'Rural Municipality'),
    -- Province 4, District 410 - Parbat
    ('Modi Rural Municipality', '410', '41001', 'Rural Municipality'),
    ('Jaljala Rural Municipality', '410', '41002', 'Rural Municipality'),
    ('Kushma Urban Municipality', '410', '41003', 'Urban Municipality'),
    ('Phalebas Urban Municipality', '410', '41004', 'Urban Municipality'),
    ('Mahashila Rural Municipality', '410', '41005', 'Rural Municipality'),
    ('Bihadi Rural Municipality', '410', '41006', 'Rural Municipality'),
    ('Paiyu Rural Municipality', '410', '41007', 'Rural Municipality'),
    -- Province 4, District 411 - Baglung
    ('Baglung Urban Municipality', '411', '41101', 'Urban Municipality'),
    ('Kathekhola Rural Municipality', '411', '41102', 'Rural Municipality'),
    ('Tarakhola Rural Municipality', '411', '41103', 'Rural Municipality'),
    ('Tamankhola Rural Municipality', '411', '41104', 'Rural Municipality'),
    ('Dhorpatan Urban Municipality', '411', '41105', 'Urban Municipality'),
    ('Nisikhola Rural Municipality', '411', '41106', 'Rural Municipality'),
    ('Badigad Rural Municipality', '411', '41107', 'Rural Municipality'),
    ('Galkot Urban Municipality', '411', '41108', 'Urban Municipality'),
    ('Bareng Rural Municipality', '411', '41109', 'Rural Municipality'),
    ('Jaimuni Urban Municipality', '411', '41110', 'Urban Municipality'),
    -- Province 5, District 501 - Rukum East
    ('Putha Uttanganga Rural Municipality', '501', '50101', 'Rural Municipality'),
    ('Sisne Rural Municipality', '501', '50102', 'Rural Municipality'),
    ('Bhoome Rural Municipality', '501', '50103', 'Rural Municipality'),
    -- Province 5, District 502 - Rolpa
    ('Sunchhahari Rural Municipality', '502', '50201', 'Rural Municipality'),
    ('Thawang Rural Municipality', '502', '50202', 'Rural Municipality'),
    ('Pariwartan Rural Municipality', '502', '50203', 'Rural Municipality'),
    ('Gangadev Rural Municipality', '502', '50204', 'Rural Municipality'),
    ('Madi Rural Municipality', '502', '50205', 'Rural Municipality'),
    ('Tribeni Rural Municipality', '502', '50206', 'Rural Municipality'),
    ('Rolpa Urban Municipality', '502', '50207', 'Urban Municipality'),
    ('Runtigadhi Rural Municipality', '502', '50208', 'Rural Municipality'),
    ('Sunil Smriti Rural Municipality', '502', '50209', 'Rural Municipality'),
    ('Lungri Rural Municipality', '502', '50210', 'Rural Municipality'),
    -- Province 5, District 503 - Pyuthan
    ('Gaumukhi Rural Municipality', '503', '50301', 'Rural Municipality'),
    ('Naubahini Rural Municipality', '503', '50302', 'Rural Municipality'),
    ('Jhimaruk Rural Municipality', '503', '50303', 'Rural Municipality'),
    ('Pyuthan Urban Municipality', '503', '50304', 'Urban Municipality'),
    ('Sworgadwari Urban Municipality', '503', '50305', 'Urban Municipality'),
    ('Mandavi Rural Municipality', '503', '50306', 'Rural Municipality'),
    ('Mallarani Rural Municipality', '503', '50307', 'Rural Municipality'),
    ('Aairawati Rural Municipality', '503', '50308', 'Rural Municipality'),
    ('Sarumarani Rural Municipality', '503', '50309', 'Rural Municipality'),
    -- Province 5, District 504 - Gulmi
    ('Kali Gandaki Rural Municipality', '504', '50401', 'Rural Municipality'),
    ('Satyawoti Rural Municipality', '504', '50402', 'Rural Municipality'),
    ('Chandrakot Rural Municipality', '504', '50403', 'Rural Municipality'),
    ('Musikot Urban Municipality', '504', '50404', 'Urban Municipality'),
    ('Isma Rural Municipality', '504', '50405', 'Rural Municipality'),
    ('Malika Rural Municipality', '504', '50406', 'Rural Municipality'),
    ('Madane Rural Municipality', '504', '50407', 'Rural Municipality'),
    ('Dhurkot Rural Municipality', '504', '50408', 'Rural Municipality'),
    ('Resunga Urban Municipality', '504', '50409', 'Urban Municipality'),
    ('Gulmi Durbar Rural Municipality', '504', '50410', 'Rural Municipality'),
    ('Chhatrakot Rural Municipality', '504', '50411', 'Rural Municipality'),
    ('Ruruchhetra Rural Municipality', '504', '50412', 'Rural Municipality'),
    -- Province 5, District 505 - Arghakhanchi
    ('Chhatradev Rural Municipality', '505', '50501', 'Rural Municipality'),
    ('Malarani Rural Municipality', '505', '50502', 'Rural Municipality'),
    ('Bhumikasthan Urban Municipality', '505', '50503', 'Urban Municipality'),
    ('Sandhikharka Urban Municipality', '505', '50504', 'Urban Municipality'),
    ('Panini Rural Municipality', '505', '50505', 'Rural Municipality'),
    ('Shitaganga Urban Municipality', '505', '50506', 'Urban Municipality'),
    -- Province 5, District 506 - Palpa
    ('Rampur Urban Municipality', '506', '50601', 'Urban Municipality'),
    ('Purbakhola Rural Municipality', '506', '50602', 'Rural Municipality'),
    ('Rambha Rural Municipality', '506', '50603', 'Rural Municipality'),
    ('Baganaskali Rural Municipality', '506', '50604', 'Rural Municipality'),
    ('Tansen Urban Municipality', '506', '50605', 'Urban Municipality'),
    ('Ribdikot Rural Municipality', '506', '50606', 'Rural Municipality'),
    ('Rainadevi Chhahara Rural Municipality', '506', '50607', 'Rural Municipality'),
    ('Tinau Rural Municipality', '506', '50608', 'Rural Municipality'),
    ('Mathagadhi Rural Municipality', '506', '50609', 'Rural Municipality'),
    ('Nisdi Rural Municipality', '506', '50610', 'Rural Municipality'),
    -- Province 5, District 507 - Nawalparasi West
    ('Bardaghat Urban Municipality', '507', '50701', 'Urban Municipality'),
    ('Sunawal Urban Municipality', '507', '50702', 'Urban Municipality'),
    ('Ramgram Urban Municipality', '507', '50703', 'Urban Municipality'),
    ('Palhinandan Rural Municipality', '507', '50704', 'Rural Municipality'),
    ('Sarawal Rural Municipality', '507', '50705', 'Rural Municipality'),
    ('Pratapapur Rural Municipality', '507', '50706', 'Rural Municipality'),
    ('Susta Rural Municipality', '507', '50707', 'Rural Municipality'),
    -- Province 5, District 508 - Rupandehi
    ('Devdaha Urban Municipality', '508', '50801', 'Urban Municipality'),
    ('Butwal Sub-Metropolitian City', '508', '50802', 'Sub-Metropolitan City'),
    ('Sainamaina Urban Municipality', '508', '50803', 'Urban Municipality'),
    ('Kanchan Rural Municipality', '508', '50804', 'Rural Municipality'),
    ('Gaidahawa Rural Municipality', '508', '50805', 'Rural Municipality'),
    ('Suddhodhan Rural Municipality', '508', '50806', 'Rural Municipality'),
    ('Siyari Rural Municipality', '508', '50807', 'Rural Municipality'),
    ('Tilottama Urban Municipality', '508', '50808', 'Urban Municipality'),
    ('Om Satiya Rural Municipality', '508', '50809', 'Rural Municipality'),
    ('Rohini Rural Municipality', '508', '50810', 'Rural Municipality'),
    ('Siddharthanagar Urban Municipality', '508', '50811', 'Urban Municipality'),
    ('Mayadevi Rural Municipality', '508', '50812', 'Rural Municipality'),
    ('Lumbini Sanskritik Urban Municipality', '508', '50813', 'Urban Municipality'),
    ('Kotahimai Rural Municipality', '508', '50814', 'Rural Municipality'),
    ('Sammarimai Rural Municipality', '508', '50815', 'Rural Municipality'),
    ('Marchawari Rural Municipality', '508', '50816', 'Rural Municipality'),
    -- Province 5, District 509 - Kapilbastu
    ('Banganga Urban Municipality', '509', '50901', 'Urban Municipality'),
    ('Buddhabhumi Urban Municipality', '509', '50902', 'Urban Municipality'),
    ('Shivaraj Urban Municipality', '509', '50903', 'Urban Municipality'),
    ('Bijayanagar Rural Municipality', '509', '50904', 'Rural Municipality'),
    ('Krishnanagar Urban Municipality', '509', '50905', 'Urban Municipality'),
    ('Maharajganj Urban Municipality', '509', '50906', 'Urban Municipality'),
    ('Kapilbastu Urban Municipality', '509', '50907', 'Urban Municipality'),
    ('Yasodhara Rural Municipality', '509', '50908', 'Rural Municipality'),
    ('Mayadevi Rural Municipality', '509', '50909', 'Rural Municipality'),
    ('Shuddhodhan Rural Municipality', '509', '50910', 'Rural Municipality'),
    -- Province 5, District 510 - Dang
    ('Bangalachuli Rural Municipality', '510', '51001', 'Rural Municipality'),
    ('Ghorahi Sub-Metropolitian City', '510', '51002', 'Sub-Metropolitan City'),
    ('Tulsipur Sub-Metropolitian City', '510', '51003', 'Sub-Metropolitan City'),
    ('Shantinagar Rural Municipality', '510', '51004', 'Rural Municipality'),
    ('Babai Rural Municipality', '510', '51005', 'Rural Municipality'),
    ('Dangisharan Rural Municipality', '510', '51006', 'Rural Municipality'),
    ('Lamahi Urban Municipality', '510', '51007', 'Urban Municipality'),
    ('Rapti Rural Municipality', '510', '51008', 'Rural Municipality'),
    ('Gadhawa Rural Municipality', '510', '51009', 'Rural Municipality'),
    ('Rajpur Rural Municipality', '510', '51010', 'Rural Municipality'),
    -- Province 5, District 511 - Banke
    ('Rapti Sonari Rural Municipality', '511', '51101', 'Rural Municipality'),
    ('Kohalpur Urban Municipality', '511', '51102', 'Urban Municipality'),
    ('Baijanath Rural Municipality', '511', '51103', 'Rural Municipality'),
    ('Khajura Rural Municipality', '511', '51104', 'Rural Municipality'),
    ('Janaki Rural Municipality', '511', '51105', 'Rural Municipality'),
    ('Nepalganj Sub-Metropolitian City', '511', '51106', 'Sub-Metropolitan City'),
    ('Duduwa Rural Municipality', '511', '51107', 'Rural Municipality'),
    ('Narainapur Rural Municipality', '511', '51108', 'Rural Municipality'),
    -- Province 5, District 512 - Bardiya
    ('Bansgadhi Urban Municipality', '512', '51201', 'Urban Municipality'),
    ('Barbardiya Urban Municipality', '512', '51202', 'Urban Municipality'),
    ('Thakurbaba Urban Municipality', '512', '51203', 'Urban Municipality'),
    ('Geruwa Rural Municipality', '512', '51204', 'Rural Municipality'),
    ('Rajapur Urban Municipality', '512', '51205', 'Urban Municipality'),
    ('Madhuwan Urban Municipality', '512', '51206', 'Urban Municipality'),
    ('Gulariya Urban Municipality', '512', '51207', 'Urban Municipality'),
    ('Badhaiyatal Rural Municipality', '512', '51208', 'Rural Municipality'),
    -- Province 6, District 601 - Dolpa
    ('Dolpo Buddha Rural Municipality', '601', '60101', 'Rural Municipality'),
    ('Shey Phoksundo Rural Municipality', '601', '60102', 'Rural Municipality'),
    ('Jagadulla Rural Municipality', '601', '60103', 'Rural Municipality'),
    ('Mudkechula Rural Municipality', '601', '60104', 'Rural Municipality'),
    ('Tripurasundari Urban Municipality', '601', '60105', 'Urban Municipality'),
    ('Thulibheri Urban Municipality', '601', '60106', 'Urban Municipality'),
    ('Kaike Rural Municipality', '601', '60107', 'Rural Municipality'),
    ('Chharka Tangsong Rural Municipality', '601', '60108', 'Rural Municipality'),
    -- Province 6, District 602 - Mugu
    ('Mugumakarmarog Rural Municipality', '602', '60201', 'Rural Municipality'),
    ('Chhayanath Rara Urban Municipality', '602', '60202', 'Urban Municipality'),
    ('Soru Rural Municipality', '602', '60203', 'Rural Municipality'),
    ('Khatyad Rural Municipality', '602', '60204', 'Rural Municipality'),
    -- Province 6, District 603 - Humla
    ('Chankheli Rural Municipality', '603', '60301', 'Rural Municipality'),
    ('Kharpunath Rural Municipality', '603', '60302', 'Rural Municipality'),
    ('Simkot Rural Municipality', '603', '60303', 'Rural Municipality'),
    ('Namkha Rural Municipality', '603', '60304', 'Rural Municipality'),
    ('Sarkegad Rural Municipality', '603', '60305', 'Rural Municipality'),
    ('Adanchuli Rural Municipality', '603', '60306', 'Rural Municipality'),
    ('Tanjakot Rural Municipality', '603', '60307', 'Rural Municipality'),
    -- Province 6, District 604 - Jumla
    ('Patarasi Rural Municipality', '604', '60401', 'Rural Municipality'),
    ('Kanaka Sundari Rural Municipality', '604', '60402', 'Rural Municipality'),
    ('Sinja Rural Municipality', '604', '60403', 'Rural Municipality'),
    ('Chandannath Urban Municipality', '604', '60404', 'Urban Municipality'),
    ('Guthichaur Rural Municipality', '604', '60405', 'Rural Municipality'),
    ('Tatopani Rural Municipality', '604', '60406', 'Rural Municipality'),
    ('Tila Rural Municipality', '604', '60407', 'Rural Municipality'),
    ('Hima Rural Municipality', '604', '60408', 'Rural Municipality'),
    -- Province 6, District 605 - Kalikot
    ('Palata Rural Municipality', '605', '60501', 'Rural Municipality'),
    ('Pachal Jharana Rural Municipality', '605', '60502', 'Rural Municipality'),
    ('Raskot Urban Municipality', '605', '60503', 'Urban Municipality'),
    ('Sanni Tribeni Rural Municipality', '605', '60504', 'Rural Municipality'),
    ('Naraharinath Rural Municipality', '605', '60505', 'Rural Municipality'),
    ('Khandachakra Urban Municipality', '605', '60506', 'Urban Municipality'),
    ('Tilagupha Urban Municipality', '605', '60507', 'Urban Municipality'),
    ('Mahawai Rural Municipality', '605', '60508', 'Rural Municipality'),
    ('Shuva Kalika Rural Municipality', '605', '60509', 'Rural Municipality'),
    -- Province 6, District 606 - Dailekh
    ('Naumule Rural Municipality', '606', '60601', 'Rural Municipality'),
    ('Mahabu Rural Municipality', '606', '60602', 'Rural Municipality'),
    ('Bhairabi Rural Municipality', '606', '60603', 'Rural Municipality'),
    ('Thantikandh Rural Municipality', '606', '60604', 'Rural Municipality'),
    ('Aathbis Urban Municipality', '606', '60605', 'Urban Municipality'),
    ('Chamunda Bindrasaini Urban Municipality', '606', '60606', 'Urban Municipality'),
    ('Dullu Urban Municipality', '606', '60607', 'Urban Municipality'),
    ('Narayan Urban Municipality', '606', '60608', 'Urban Municipality'),
    ('Bhagawatimai Rural Municipality', '606', '60609', 'Rural Municipality'),
    ('Dungeshwor Rural Municipality', '606', '60610', 'Rural Municipality'),
    ('Gurans Rural Municipality', '606', '60611', 'Rural Municipality'),
    -- Province 6, District 607 - Jajarkot
    ('Barekot Rural Municipality', '607', '60701', 'Rural Municipality'),
    ('Kushe Rural Municipality', '607', '60702', 'Rural Municipality'),
    ('Junichande Rural Municipality', '607', '60703', 'Rural Municipality'),
    ('Chhedagad Urban Municipality', '607', '60704', 'Urban Municipality'),
    ('Shivalaya Rural Municipality', '607', '60705', 'Rural Municipality'),
    ('Bheri Malika Urban Municipality', '607', '60706', 'Urban Municipality'),
    ('Nalgad Urban Municipality', '607', '60707', 'Urban Municipality'),
    -- Province 6, District 608 - Rukum West
    ('Aathabisakot Urban Municipality', '608', '60801', 'Urban Municipality'),
    ('Sanibheri Rural Municipality', '608', '60802', 'Rural Municipality'),
    ('Banphikot Rural Municipality', '608', '60803', 'Rural Municipality'),
    ('Musikot Urban Municipality', '608', '60804', 'Urban Municipality'),
    ('Tribeni Rural Municipality', '608', '60805', 'Rural Municipality'),
    ('Chaurjahari Urban Municipality', '608', '60806', 'Urban Municipality'),
    -- Province 6, District 609 - Salyan
    ('Darma Rural Municipality', '609', '60901', 'Rural Municipality'),
    ('Kumakh Rural Municipality', '609', '60902', 'Rural Municipality'),
    ('Banagad Kupinde Urban Municipality', '609', '60903', 'Urban Municipality'),
    ('Siddha Kumakh Rural Municipality', '609', '60904', 'Rural Municipality'),
    ('Bagachour Urban Municipality', '609', '60905', 'Urban Municipality'),
    ('Chhatreshwori Rural Municipality', '609', '60906', 'Rural Municipality'),
    ('Sharada Urban Municipality', '609', '60907', 'Urban Municipality'),
    ('Kalimati Rural Municipality', '609', '60908', 'Rural Municipality'),
    ('Tribeni Rural Municipality', '609', '60909', 'Rural Municipality'),
    ('Kapurkot Rural Municipality', '609', '60910', 'Rural Municipality'),
    -- Province 6, District 610 - Surkhet
    ('Simta Rural Municipality', '610', '61001', 'Rural Municipality'),
    ('Chingad Rural Municipality', '610', '61002', 'Rural Municipality'),
    ('Lekabeshi Urban Municipality', '610', '61003', 'Urban Municipality'),
    ('Gurbhakot Urban Municipality', '610', '61004', 'Urban Municipality'),
    ('Bheriganga Urban Municipality', '610', '61005', 'Urban Municipality'),
    ('Birendranagar Urban Municipality', '610', '61006', 'Urban Municipality'),
    ('Barahatal Rural Municipality', '610', '61007', 'Rural Municipality'),
    ('Panchapuri Urban Municipality', '610', '61008', 'Urban Municipality'),
    ('Chaukune Rural Municipality', '610', '61009', 'Rural Municipality'),
    -- Province 7, District 701 - Bajura
    ('Himali Rural Municipality', '701', '70101', 'Rural Municipality'),
    ('Gaumul Rural Municipality', '701', '70102', 'Rural Municipality'),
    ('Budhinanda Urban Municipality', '701', '70103', 'Urban Municipality'),
    ('Swamikartik Khapar Rural Municipality', '701', '70104', 'Rural Municipality'),
    ('Jagannath Rural Municipality', '701', '70105', 'Rural Municipality'),
    ('Badimalika Urban Municipality', '701', '70106', 'Urban Municipality'),
    ('Khaptad Chhededaha Rural Municipality', '701', '70107', 'Rural Municipality'),
    ('Budhiganga Urban Municipality', '701', '70108', 'Urban Municipality'),
    ('Tribeni Urban Municipality', '701', '70109', 'Urban Municipality'),
    -- Province 7, District 702 - Bajhang
    ('Saipal Rural Municipality', '702', '70201', 'Rural Municipality'),
    ('Bungal Urban Municipality', '702', '70202', 'Urban Municipality'),
    ('Surma Rural Municipality', '702', '70203', 'Rural Municipality'),
    ('Talkot Rural Municipality', '702', '70204', 'Rural Municipality'),
    ('Masta Rural Municipality', '702', '70205', 'Rural Municipality'),
    ('Jayaprithbi Urban Municipality', '702', '70206', 'Urban Municipality'),
    ('Chhabis Pathibhara Rural Municipality', '702', '70207', 'Rural Municipality'),
    ('Durgathali Rural Municipality', '702', '70208', 'Rural Municipality'),
    ('Kedarsyun Rural Municipality', '702', '70209', 'Rural Municipality'),
    ('Bitthadchir Rural Municipality', '702', '70210', 'Rural Municipality'),
    ('Thalara Rural Municipality', '702', '70211', 'Rural Municipality'),
    ('Khaptad Chhanna Rural Municipality', '702', '70212', 'Rural Municipality'),
    -- Province 7, District 703 - Darchula
    ('Byas Rural Municipality', '703', '70301', 'Rural Municipality'),
    ('Duhun Rural Municipality', '703', '70302', 'Rural Municipality'),
    ('Mahakali Urban Municipality', '703', '70303', 'Urban Municipality'),
    ('Naugad Rural Municipality', '703', '70304', 'Rural Municipality'),
    ('Apihimal Rural Municipality', '703', '70305', 'Rural Municipality'),
    ('Marma Rural Municipality', '703', '70306', 'Rural Municipality'),
    ('Shailyashikhar Urban Municipality', '703', '70307', 'Urban Municipality'),
    ('Malikarjun Rural Municipality', '703', '70308', 'Rural Municipality'),
    ('Lekam Rural Municipality', '703', '70309', 'Rural Municipality'),
    -- Province 7, District 704 - Baitadi
    ('Dilasaini Rural Municipality', '704', '70401', 'Rural Municipality'),
    ('Dogada Kedar Rural Municipality', '704', '70402', 'Rural Municipality'),
    ('Puchaundi Urban Municipality', '704', '70403', 'Urban Municipality'),
    ('Surnaya Rural Municipality', '704', '70404', 'Rural Municipality'),
    ('Dasharathchand Urban Municipality', '704', '70405', 'Urban Municipality'),
    ('Pancheshwor Rural Municipality', '704', '70406', 'Rural Municipality'),
    ('Shivanath Rural Municipality', '704', '70407', 'Rural Municipality'),
    ('Melauli Urban Municipality', '704', '70408', 'Urban Municipality'),
    ('Patan Urban Municipality', '704', '70409', 'Urban Municipality'),
    ('Sigas Rural Municipality', '704', '70410', 'Rural Municipality'),
    -- Province 7, District 705 - Dadeldhura
    ('Nawadurga Rural Municipality', '705', '70501', 'Rural Municipality'),
    ('Amargadhi Urban Municipality', '705', '70502', 'Urban Municipality'),
    ('Ajayameru Rural Municipality', '705', '70503', 'Rural Municipality'),
    ('Bhageshwor Rural Municipality', '705', '70504', 'Rural Municipality'),
    ('Parashuram Urban Municipality', '705', '70505', 'Urban Municipality'),
    ('Aalital Rural Municipality', '705', '70506', 'Rural Municipality'),
    ('Ganyapdhura Rural Municipality', '705', '70507', 'Rural Municipality'),
    -- Province 7, District 706 - Doti
    ('Purbichouki Rural Municipality', '706', '70601', 'Rural Municipality'),
    ('Sayal Rural Municipality', '706', '70602', 'Rural Municipality'),
    ('Aadarsha Rural Municipality', '706', '70603', 'Rural Municipality'),
    ('Shikhar Urban Municipality', '706', '70604', 'Urban Municipality'),
    ('Dipayal Silgadhi Urban Municipality', '706', '70605', 'Urban Municipality'),
    ('K.I. Singh Rural Municipality', '706', '70606', 'Rural Municipality'),
    ('Bogatan Phudsil Rural Municipality', '706', '70607', 'Rural Municipality'),
    ('Badi Kedar Rural Municipality', '706', '70608', 'Rural Municipality'),
    ('Jorayal Rural Municipality', '706', '70609', 'Rural Municipality'),
    -- Province 7, District 707 - Achham
    ('Panchdebal Binayak Urban Municipality', '707', '70701', 'Urban Municipality'),
    ('Ramaroshan Rural Municipality', '707', '70702', 'Rural Municipality'),
    ('Mellekh Rural Municipality', '707', '70703', 'Rural Municipality'),
    ('Sanphebagar Urban Municipality', '707', '70704', 'Urban Municipality'),
    ('Chaurpati Rural Municipality', '707', '70705', 'Rural Municipality'),
    ('Mangalsen Urban Municipality', '707', '70706', 'Urban Municipality'),
    ('Bannigadhi Jayagadh Rural Municipality', '707', '70707', 'Rural Municipality'),
    ('Kamal bazar Urban Municipality', '707', '70708', 'Urban Municipality'),
    ('Dhakari Rural Municipality', '707', '70709', 'Rural Municipality'),
    ('Turmakhand Rural Municipality', '707', '70710', 'Rural Municipality'),
    -- Province 7, District 708 - Kailali
    ('Mohanyal Rural Municipality', '708', '70801', 'Rural Municipality'),
    ('Chure Rural Municipality', '708', '70802', 'Rural Municipality'),
    ('Godawari Urban Municipality', '708', '70803', 'Urban Municipality'),
    ('Gauriganga Urban Municipality', '708', '70804', 'Urban Municipality'),
    ('Ghodaghodi Urban Municipality', '708', '70805', 'Urban Municipality'),
    ('Bardagoriya Rural Municipality', '708', '70806', 'Rural Municipality'),
    ('Lamki Chuha Urban Municipality', '708', '70807', 'Urban Municipality'),
    ('Janaki Rural Municipality', '708', '70808', 'Rural Municipality'),
    ('Joshipur Rural Municipality', '708', '70809', 'Rural Municipality'),
    ('Tikapur Urban Municipality', '708', '70810', 'Urban Municipality'),
    ('Bhajani Urban Municipality', '708', '70811', 'Urban Municipality'),
    ('Kailari Rural Municipality', '708', '70812', 'Rural Municipality'),
    ('Dhangadhi Sub-Metropolitian City', '708', '70813', 'Sub-Metropolitan City'),
    -- Province 7, District 709 - Kanchanpur
    ('Krishnapur Urban Municipality', '709', '70901', 'Urban Municipality'),
    ('Shuklaphanta Urban Municipality', '709', '70902', 'Urban Municipality'),
    ('Bedkot Urban Municipality', '709', '70903', 'Urban Municipality'),
    ('Bhimdatta Urban Municipality', '709', '70904', 'Urban Municipality'),
    ('Mahakali Urban Municipality', '709', '70905', 'Urban Municipality'),
    ('Laljhadi Rural Municipality', '709', '70906', 'Rural Municipality'),
    ('Punarbas Urban Municipality', '709', '70907', 'Urban Municipality'),
    ('Belouri Urban Municipality', '709', '70908', 'Urban Municipality'),
    ('Beldandi Rural Municipality', '709', '70909', 'Rural Municipality');
END
GO
